language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra-android-m2repository

jdk: oraclejdk8

before_install:
- yes | sdkmanager "platforms;android-30"

script:
- ./gradlew assemble

branches:
  except:
  - gh-pages

cache:
  directories:
    - $HOME/.gradle

sudo: false

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: HJUAv6rWaIhA/89n/AxfOj1qz4rRJMPxEPOWEKxUPmWyHQkmzSdzuo5kanZrgEf+U+tORExG64useHKmtez9qG6EtzpBCA1AFM+ASqaeg8EXg1Ca34KFrVzUE+1WrngmFKWRHEGHrY+TBgCdi636eBD+22b88Et6Fisd86C/5CtkSuqmNa9K7ehjOvwsY5g1ejhC7BNcFgfHCWF/A3n+Pv9WhgsD/nNHvcEBx/uUntB6KSYhMRDMNPrVhksTHuqQhJzmwfkvZbU/g95kRRMHRACTlanejwz+4aCeuYksdcOo3TjOfzwhaviTmAWJws/dJcYiA8zPPcIbq07vwAOxBpOEDHHin+AZLF1iHjaApLdWejimqW/3bKPupx375mVJmOYj9qBRGoE6Fa+Ch6gkFsblArEfLmv1wqrk3O9/O6U+7Pl9jI4dT1GfeLfzum6VyyBpGrYHowS9GFhg5p3TDp1vv0b7IRpLgDBMCw/sG/6+f49Ewp7jPCbtPLn8JPHLg5Vxh5Lz1ElWDgcclZ3kaqSZsscZkAjlKhvSMMWoCPR7C3x4mJkRI4KGUgm/+Q5M7CgkjKkNwuzZceAo9xEefwjhGo8Dfo2izbcJ2BoYezWJivUJHl9tvcikgKlWdGHEGq15SaVO01KP2Y1xjyrlCNI/Sm1lW2N56MmWBzx95oY=
  file:
  - "tools-*/build/outputs/aar/tools-*-debug.aar"
  - "tools-*/build/outputs/aar/tools-*-release.aar"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: wrabot/AndroidKotlinTools
